In [1]:
import numpy as np


In [5]:
a=np.array([1,2,3])
print type(a),a.shape, a[0],a[1],a[2]
a[0]=5
print (a)


SyntaxError: invalid syntax (<ipython-input-5-9f5184ba0cd7>, line 2)

In [7]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
print( b.shape)
print (b[0,0],b[0,1],b[1,0])

(2, 3)
1 2 4


In [13]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [15]:
b=np.ones((1,2))
print(b)

[[1. 1.]]


In [17]:
c=np.full((2),7)
print(c)

[7 7]


In [18]:
d=np.eye(2)
print (d)

[[1. 0.]
 [0. 1.]]


In [22]:
e=np.random.random((2,2))
print (e)

[[0.50911184 0.48229427]
 [0.28762498 0.11446812]]


In [23]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [30]:
import numpy as np
x=np.arange(0,3*np.pi,0.1)
y=np.sin(x)
y_cos=np.cos(x)
Plt.plot(x,y)


NameError: name 'Plt' is not defined